const app = getApp();
const { aggregate } = require('../../utils/weeklyAggregator.js');

Page({
  data:{ mode:'week', offset:0, dataObj:{}, moodKeys:[] },
  onShow(){ this.loadData(); },
  switchMode(e){ const m=e.currentTarget.dataset.m; if(m===this.data.mode) return; this.setData({ mode:m, offset:0 },()=> this.loadData()); },
  prevRange(){ this.setData({ offset:this.data.offset-1 },()=> this.loadData()); },
  nextRange(){ if(this.data.offset>=0) return; this.setData({ offset:this.data.offset+1 },()=> this.loadData()); },
  resolveSkill(id){ if(id==='其他') return '未关联'; const s=(app.globalData.skills||[]).find(x=>x.id===id); return s? s.name:'未知'; },
  loadData(){
    const ref = new Date();
    if(this.data.mode==='week'){
      ref.setDate(ref.getDate() + this.data.offset*7);
      const ag=aggregate(app.globalData,{ type:'week', refDate:ref });
      this.setData({ dataObj:ag, moodKeys:Object.keys(ag.moodDistribution||{}) });
    } else {
      ref.setMonth(ref.getMonth()+ this.data.offset);
      const ag=aggregate(app.globalData,{ type:'month', refDate:ref });
      this.setData({ dataObj:ag, moodKeys:Object.keys(ag.moodDistribution||{}) });
    }
  },
  genShare(){
    const query=wx.createSelectorQuery();
    query.select('#shareCanvas').fields({ node:true, size:true }).exec(res=>{
      const r=res[0]; if(!r||!r.node) return wx.showToast({ title:'不支持', icon:'none' });
      const canvas=r.node; const ctx=canvas.getContext('2d'); const W=750; const H=1000; canvas.width=W; canvas.height=H;
      ctx.fillStyle='#ffffff'; ctx.fillRect(0,0,W,H);
      ctx.fillStyle='#111'; ctx.font='32px sans-serif'; ctx.fillText(this.data.mode==='week'?'本周回顾':'本月回顾',40,60);
      ctx.font='22px sans-serif';
      const ag=this.data.dataObj; let y=120; const lineH=34;
      const lines=[
        `范围: ${ag.label}`,
        `储蓄率: ${ag.savingsRate}%`,
        `净资产变化≈: ${ag.netAssetChange}`,
        `被动收入增量: ${ag.passiveIncomeDelta}`,
        `番茄总时长: ${ag.focusMinutesTotal} 分钟`,
        `习惯完成率: ${ag.habitCompletionRate}%`
      ];
      lines.forEach(l=>{ ctx.fillText(l,40,y); y+=lineH; });
      y+=20; ctx.fillText('Top 支出类别:',40,y); y+=lineH;
      (ag.topExpenseCategories||[]).forEach(t=>{ ctx.fillText(`${t.category}: ${t.amount}`,60,y); y+=lineH; });
      y+=10; ctx.fillText('Top 技能小时:',40,y); y+=lineH;
      (ag.topSkillHours||[]).forEach(t=>{ ctx.fillText(`${this.resolveSkill(t.skillId)}: ${t.hours}h`,60,y); y+=lineH; });
      y+=10; ctx.fillText('心情分布:',40,y); y+=lineH;
      Object.keys(ag.moodDistribution||{}).forEach(k=>{ ctx.fillText(`${k}: ${ag.moodDistribution[k]}`,60,y); y+=lineH; });
      ctx.fillStyle='#3366ff'; ctx.font='20px sans-serif'; ctx.fillText('Generated by 成长加速器',40,H-60);
      try{ wx.canvasToTempFilePath({ canvas, success:res2=>{ const path=res2.tempFilePath; wx.previewImage({ urls:[path] }); }}); }catch(err){ console.error(err); wx.showToast({ title:'导出失败', icon:'none' }); }
    });
  }
});
